import { CustomTailwindStyles } from "./components/custom-tailwind-styles/custom-tailwind-styles";
import { NavBar } from "./components/navbar/navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Tailwind Configuration editor",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<CustomTailwindStyles />
			</head>

			<body className={inter.className}>
				<header>
					<NavBar />
				</header>

				{children}
			</body>
		</html>
	);
}
